dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /workspaces/predictive-oee-phm-engine/dbt/factory_analytics.db
      threads: 4
      extensions:
        - json
        - parquet
        - excel
